### ISSUE TITLE
More currency-related info will be appreciated

### ISSUE THREAD

**Issue by EsteveAguilera** [Daniel-Ioannou/flutter_currency_picker#16]
Letting the user select the currency has some impacts not only on the currency name/symbol to show.

There are some currencies that show the symbol before the amount while others after. There're also some currencies that are a space between the symbol and the amount, and not all currencies show the same decimal digits.

I think that gives this information when the user selects a currency will be really helpful.

I've found a JSON file from another library that has this information, so it will not be too hard to add it:

https://github.com/smirzaei/currency-formatter/blob/master/currencies.json

**Comment by voivoed** [comment]
@Daniel-Ioannou are you planning to add the extra formatting info from the JSON file @EsteveAguilera provided?

**Comment by EsteveAguilera** [comment]
I can work on a PR to add the currency symbol location if you're interested

**Comment by voivoed** [comment]
I was going to offer if Daniel wasn't planning to, but if you have the time to do it, that would make my life easier :-) I'm on a tight deadline for another project.

Could you also add the other info: "thousandsSeparator", "decimalSeparator", "symbolOnLeft" and    "spaceBetweenAmountAndSymbol"? That way the info can be used to do custom formatting for currencies not supported by intl (which is what I need).

**Comment by Daniel-Ioannou** [comment]
@voivoed @EsteveAguilera I already add some fields. I'm working on it now 🙂

**Comment by Daniel-Ioannou** [comment]
I will post the changes tomorrow, it is past midnight here now.
