### ISSUE TITLE
Incorrect currency symbols

### ISSUE THREAD

**Issue by voivoed** [Daniel-Ioannou/flutter_currency_picker#19]
I went over all the currency symbols after I noticed one of them (KZT) didn't seem right, and found that some may be incorrect. As far as I can tell by looking at a number of websites**, these seem to be the right symbols for the following currencies:

```
AMD ֏
BYN Br
GHS ₵
KZT 〒
MDL L
PYG ₲
RON L
```

** these 2 seem to be the most complete references I found. I tried to go with the most agreed upon symbols. The second link says those are the ISO codes, but iso.org charges $41 for the PDF with the codes, so I couldn't double check it... it's hard to find consistent answers on the internet.
https://en.wikipedia.org/wiki/Currency_symbol#List_of_currency_symbols_currently_in_use
https://www.foreignexchangelive.com/currency-codes-symbols/
https://github.com/smirzaei/currency-formatter/blob/master/currencies.json

**Comment by Daniel-Ioannou** [comment]
I think you are right, these symbols is the right.

As you said, it's hard to find consistent answers, it is even worse when it comes to `decimalSeparator` or `symbolOnLeft`. For example the majority of countries that use euro write the symbol after the amount but some countries write the symbol before the amount. Check [this table](https://en.wikipedia.org/wiki/Language_and_the_euro#Summary) on Wikipedia.
