### ISSUE TITLE
The currencies shouldn't know about the decimal and the thousands separator

### ISSUE THREAD

**Issue by rocboronat** [Daniel-Ioannou/flutter_currency_picker#30]
Hello!

Playing around with the picker, I've noticed the `Currency` class has `decimalSeparator` and `thousandsSeparator` fields.

I think they shouldn't, because that is related with the device language, not the currency itself.

An example: in Catalan and Spanish, we use the comma as a decimal separator and the dot as a thousand separator for both numbers and currencies. And the opposite: in English, the comma is for the thousands and the dot for the decimals, for both numbers and currencies.

What do you think?

Thanks!

**Comment by Daniel-Ioannou** [comment]
@rocboronat Each country uses different thousand separator for numbers but when it comes to currencies, each currency has different thousand and decimal separator.

I agree with you is more common to use country preference for thousand and decimal separator but if some developers want to use Currency thousand and decimal separator they have the option through the package.

An example: Euro use comma as a decimal separator but not all countries that use the euro as their currency use comma for decimal separator. Cyprus use dot as decimal separator (234.56) but for amount use comma(€234,56).

**Comment by rocboronat** [comment]
Totally agree with you example! 😄 But that could be a good reason to avoid relating the currency with the comma or dot, isn't it...?

**Comment by rocboronat** [comment]
Then, let's leave it as it is. Thanks a lot for having thought about it! 👍
