### ISSUE TITLE
Add the Seychellois rupees

### ISSUE THREAD

**Issue by rocboronat** [Daniel-Ioannou/flutter_currency_picker#37]
Hello Daniel! I wanted to make a PR to add the Seychellois rupees to the list of currencies but I'm not sure about the `number` field. And I don't have the flag yet. So I'm opening an issue in case you can add it easily, or as a reminder for me to make the PR :·)

Here's what I have atm:

```dart
{
    "code": "SCR",
    "name": "Seychellois rupee",
    "symbol": "₨",
    "flag": "BY",
    "decimal_digits": 2,
    "number": TBD,
    "name_plural": "Seychellois rupees",
    "thousands_separator": ".",
    "decimal_separator": ",",
    "space_between_amount_and_symbol": true,
    "symbol_on_left": true,
},
```

**Comment by Daniel-Ioannou** [comment]
Hello @rocboronat `number` field is defined by [ISO 4217](https://en.wikipedia.org/wiki/ISO_4217), for Seychellois rupee is **690** and `flag` is **SC**. 

Btw the name is **Seychelles rupee** or **Seychellois rupee**?


```dart
{
    "code": "SCR",
    "name": "Seychellois rupee",
    "symbol": "₨",
    "flag": "SC",
    "decimal_digits": 2,
    "number": 690,
    "name_plural": "Seychellois rupees",
    "thousands_separator": ".",
    "decimal_separator": ",",
    "space_between_amount_and_symbol": true,
    "symbol_on_left": true,
},
```

**Comment by rocboronat** [comment]
You're right! Just checked the currencies naming style and I would say it's just Seychelles. Thanks for checking! 😊 I'll apply it to the PR and leave it ready to merge asap.

**Comment by rocboronat** [comment]
Let's move this issue to its PR in #48. Thanks for the support, @Daniel-Ioannou!
