### ISSUE TITLE
Add Riel Currrency

### ISSUE THREAD

**Issue by pckimlong** [Daniel-Ioannou/flutter_currency_picker#42]
{
    "code": "KHR",
    "name": "Khmer Riel",
    "symbol": "៛",
    "flag": "",
    "decimal_digits": 2,
    "number": ,
    "name_plural": "riels",
    "thousands_separator": ",",
    "decimal_separator": ".",
    "space_between_amount_and_symbol": false,
    "symbol_on_left": false,
  },

**Comment by Daniel-Ioannou** [comment]
Released in [v2.0.10](https://pub.dev/packages/currency_picker/versions/2.0.10).
