### ISSUE TITLE
Implement the option to add custom hint for the Search and the option to show/hide the currency name 

### ISSUE THREAD

**Issue by FRANIAZA** [Daniel-Ioannou/flutter_currency_picker#5]
Please add the possibility to specify a custom hint instead of the default "Search", and add the option to show or not show the subtitles in each element of the list.
Thank you :)

**Comment by Daniel-Ioannou** [comment]
@FRANIAZA Thank you for the suggestions, I will implement them in the next few days.

**Comment by Daniel-Ioannou** [comment]
- `searchHint`: Option to customize hint of the search TextField
 - `showCurrencyName`: Option to show/hide the currency name
 - `showCurrencyCode`: Option to show/hide the currency code
```Dart
showCurrencyPicker(
   context: context,
   showFlag: true,
   searchHint: 'Search here',
   showCurrencyName: true,
   showCurrencyCode: true,
   onSelect: (Currency currency) {
      print('Select currency: ${currency.name}');
   },
);
```

Note: `showCurrencyCode` and `showCurrencyName` cannot be both false
