### ISSUE TITLE
Not able to change the color of search icon in the popup

### ISSUE THREAD

**Issue by Charlinjoeaht** [Daniel-Ioannou/flutter_currency_picker#75]
Not able to change the color of search icon in the popup

![image](https://user-images.githubusercontent.com/50817246/223700104-66a3d84b-8f84-4a2d-8ba3-fc774d2e4c9f.png)

**Comment by iabdousd** [comment]
I think the whole InputDecoration of the search field can be a parameter that you pass to the `showCurrencyPicker` function, I will make that change

**Comment by iabdousd** [comment]
Created a PR to solve this: #78

**Comment by Charlinjoeaht** [comment]
Thanks @iabdousd. Eager to use this feature

**Comment by Daniel-Ioannou** [comment]
@Charlinjoeaht Released in [v2.0.18](https://pub.dev/packages/currency_picker/versions/2.0.18).

**Comment by Charlinjoeaht** [comment]
The changes look pretty good. Thanks for this release
